### ISSUE TITLE
Matomo Marketplace reports v1.1.1, but this repo reports v1.1.0

### ISSUE THREAD

**Issue by dlecan** [ronan-hello/matomo-kpi-widgets#2]
Hi,

I install Matomo plugins with Git, so from Github sources.

After a fresh installation this morning of this plugin (v1.1.0, according to https://github.com/ronan-hello/matomo-kpi-widgets/blob/4.x-dev/plugin.json#L4), Matomo says an update is available: v1.1.1
Where is it located?

Thank you

**Comment by ronan-hello** [comment]
Hi,

I just edited the plugin.json without publishing new tags.
tell me if it solved your problem.

I just forgot to update plugin.json while publishing last release

**Comment by dlecan** [comment]
That was ok
Thank you!
