### ISSUE TITLE
Format numbers nicely

### ISSUE THREAD

**Issue by peterbo** [ronan-hello/matomo-kpi-widgets#5]
![number-formats](https://github.com/ronan-hello/matomo-kpi-widgets/assets/1018973/8b5fb4a9-2097-4d99-a8d2-c680a7715ee2)

**Comment by ronan-hello** [comment]
Hi Peter,

Thank you for opening this issue, but this screenshot is not showing my plugin.
The issue you mention is from a Core plugin.

Regards,
Ronan

**Comment by peterbo** [comment]
Hi @ronan-hello , the upper part is not from core, as far as I know. Isn't that coming from the KPI widget plugin? The underlined part below (overview with graph) is just for comparison, because numbers are formatted correctly here.

**Comment by ronan-hello** [comment]
Hi,

Thank you for this issue, this have been fixed today

Regards,
Ronan HELLO

**Comment by peterbo** [comment]
Thank you, @ronan-hello! That's a great refinement to this plugin!

However, you were completely right and the widget from the screenshot is the KPI Metric Widget from core, which is formatted incorrectly. I somehow thought, that the KPI Widget plugin was a core plugin. Sorry!
